name: Publish to Artifact Repository

on:
  release:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Maven Test
        run: mvn -pl '!integration-tests,!examples,!coverage,!examples/quickstart' test -PemporixRepositoryAccessKey=${{ env.S3_USER }} -PemporixRepositorySecretKey=${{ env.S3_PASS }}
        env:
          S3_USER: ${{ secrets.S3_USERNAME }}
          S3_PASS: ${{ secrets.S3_PASSWORD }}
          
  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Publish to Artifact Repository
      run: |
        echo $CREDENTIALS >> tech_bucket_key.json && \
        mvn -pl '!integration-tests,!examples,!coverage,!examples/quickstart' -DskipTests deploy -PemporixRepositoryAccessKey=${{ env.S3_USER }} -PemporixRepositorySecretKey=${{ env.S3_PASS }}
      env:
        S3_USER: ${{ secrets.S3_USERNAME }}
        S3_PASS: ${{ secrets.S3_PASSWORD }}
        CREDENTIALS: ${{ secrets.TECH_ARTIFACTS_BUCKET_CREDENTIALS }}
        GOOGLE_APPLICATION_CREDENTIALS: tech_bucket_key.json
