name: Run tests

on: [ pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Maven Tests
        run:  mvn -pl '!integration-tests,!examples,!coverage,!examples/quickstart' test -PemporixRepositoryAccessKey=${{ env.S3_USER }} -PemporixRepositorySecretKey=${{ env.S3_PASS }}
        env:
          S3_USER: ${{ secrets.S3_USERNAME }}
          S3_PASS: ${{ secrets.S3_PASSWORD }}
